from .coregionalized_gp import MetaCoregionalizedGPOffgrid
from .coregionalized_rf import MetaCoregionalizedRFOffgrid
from .multioutput_gp_george import MetaMultitaskGPGeorgeOffgrid
from .randomforest import MetaRandomForestOffgrid
from .singleoutput_gp import MetaSingleOutputGPOffgrid
